module.exports = {
  "0": "Error desconocido",
  "1": "Account exist",
  "2": "Email exist",
  "3": "Tu número de teléfono está actualizado",
  "4": "Contraseña y Confirmar contraseña no coinciden",
  "5": "Esta cuenta está activada.",
  "6": "Esta cuenta no está activada.",
  "7": "!Revisa que coincida tu PIN !",
  "8": "La cuenta no existe",
  "9": "El dígito no coincide",
  "10": "This account has been active",
  "11": "No podemos verificar tu email, por favor envíanos un correo directamente a info@starmyagent.com",
  "9997": "No token",
  "9998": "Token is not valid",
  "9999": "Nombre de usuario o contraseña incorrecta",
  "10000": "No data",
  "10001": "No permission",
  "11000": "La cuenta ya existe",
  "99999": "Not Found"
};
